api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: certificates.yaml
log: {}

accessLog: {}

entryPoints:
  websecure:
    address: ":443"
  traefik:
    address: ":8080"