FROM python:3.12.2-slim

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    apt clean && \
    rm -rf /var/cache/apt/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8

COPY requirements.txt /tmp/requirements/requirements.txt

RUN pip install -U pip && \
    pip install --no-cache-dir -r /tmp/requirements/requirements.txt

COPY . /src

ENV PATH "$PATH:/src/script"

# Data path for storing uploaded files
RUN mkdir /data

# Create a non-root user
WORKDIR /src

CMD ["./script/start-api.sh"]