FROM ngocptblaplafla/pandoc-texlive-full:nightly

# Remove old entrypoint
ENTRYPOINT [ ]

# Install necessary packages
RUN apk update && \
    apk add --no-cache gcc musl-dev libpq postgresql-dev python3-dev py3-pip

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8

COPY requirements-worker.txt /tmp/requirements/requirements.txt

# Create and activate virtual environment, then install dependencies
RUN python3 -m venv /venv && \
    . /venv/bin/activate && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements/requirements.txt


ENV PATH "$PATH:/worker"

RUN mkdir /worker

WORKDIR /worker
USER app