services:
  adminer:
    image: adminer
    restart: always
    networks:
      - traefik-public
      - backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=delus
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-http.rule=Host(`adminer.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.rule=Host(`adminer.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?Variable not set}-adminer.loadbalancer.server.port=8080


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - markdown_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

  redis:
    image: redis:7.4.0
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/src
      - $DATA_FOLDER_PATH_DOCKER:/data
      - $DATA_FOLDER_PATH_ENGINE:/engine
    environment:
      - BACKEND_CORS_ORIGINS=["*"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend
      - traefik-public
    user: "${UID}:${GID}"
    working_dir: "/src"
    # command: ["fastapi", "dev", "--host", "0.0.0.0"]
    command: ["./script/start-api.sh"]
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=80

      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=(Host(`${DOMAIN?Variable not set}`) || Host(`www.${DOMAIN?Variable not set}`)) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.rule=(Host(`${DOMAIN?Variable not set}`) || Host(`www.${DOMAIN?Variable not set}`)) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls.certresolver=le

      # Define Traefik Middleware to handle domain with and without "www" to redirect to only one
      - traefik.http.middlewares.${STACK_NAME?Variable not set}-www-redirect.redirectregex.regex=^http(s)?://www.(${DOMAIN?Variable not set})/(.*)
      # Redirect a domain with www to non-www
      - traefik.http.middlewares.${STACK_NAME?Variable not set}-www-redirect.redirectregex.replacement=http$${1}://${DOMAIN?Variable not set}/$${3}

      # Enable www redirection for HTTP and HTTPS
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.middlewares=https-redirect,${STACK_NAME?Variable not set}-www-redirect
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.middlewares=${STACK_NAME?Variable not set}-www-redirect

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker.yaml
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DATA_FOLDER_PATH_DEPLOY:/engine/deploy
      - DATA_FOLDER_PATH_MARKDOWN:/data/markdown
      - DATA_FOLDER_PATH_HTML:/data/html
      - DATA_FOLDER_PATH_YAML:/data/yaml
      - REDIS_HOST=redis
    volumes:
      - ./worker:/worker
      - $DATA_FOLDER_PATH_ENGINE:/engine
      - $DATA_FOLDER_PATH_DOCKER:/data
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend
    user: "${UID}:${GID}"
    command: ["./start-worker.sh"]


volumes:
  markdown_db:

networks:
  backend:
  traefik-public:
    # Allow setting it to false for testing
    external: true