version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - markdown_db:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile.yaml
    volumes:
      - ./app:/src/app
      - $DATA_FOLDER_PATH:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker.yaml
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - $DATA_FOLDER_PATH:/data
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend

volumes:
  markdown_db:
  markdown_file_data:

networks:
  backend: