# This version is for mounting the volume in the local machine and continue developing the app

FROM python:3.12.2-slim

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    apt clean && \
    rm -rf /var/cache/apt/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8

COPY requirements.txt /tmp/requirements/requirements.txt

RUN pip install -U pip && \
    pip install --no-cache-dir -r /tmp/requirements/requirements.txt

ENTRYPOINT [ ]