FROM ngocptblaplafla/pandoc-texlive-full:v1.2-nightly

# Remove old entrypoint
ENTRYPOINT [ ]

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8

RUN --mount=type=bind,source=requirements-worker.txt,target=/tmp/requirements.txt pip3 install -r /tmp/requirements.txt

ENV PATH "$PATH:/worker"

RUN mkdir /worker

WORKDIR /worker
USER app